// backend/src/main/kotlin/com/demo/grpc/model/ProductRepository.kt
package com.demo.grpc

import com.demo.grpc.generated.Product
import com.demo.grpc.generated.product
import kotlinx.serialization.Serializable

// ─────────────────────────────────────────────────────────────
// Domain model (shared by REST and gRPC — same data source)
// This is the KEY POINT for the "side-by-side" slide:
// both transports hit the same repository.
// ─────────────────────────────────────────────────────────────
data class ProductEntity(
    val id: String,
    val name: String,
    val pricePaise: Long,
    val imageUrl: String,
    val inStock: Boolean,
    val category: String,
)

// REST DTO — used by Ktor JSON routes
@Serializable
data class ProductDto(
    val id: String,
    val name: String,
    val pricePaise: Long,
    val imageUrl: String,
    val inStock: Boolean,
    val category: String,
)

// Live-price REST DTO — used by the /price comparison endpoint.
// Deliberately tiny so the demo can still show REST is heavier per-call.
@Serializable
data class LivePriceDto(
    val productId: String,
    val pricePaise: Long,
    val currency: String  = "INR",
)

fun ProductEntity.toRestDto() = ProductDto(
    id         = id,
    name       = name,
    pricePaise = pricePaise,
    imageUrl   = imageUrl,
    inStock    = inStock,
    category   = category,
)

// gRPC Protobuf message — built using Kotlin DSL generated by protoc
fun ProductEntity.toProto(): Product = product {
    id         = this@toProto.id
    name       = this@toProto.name
    pricePaise = this@toProto.pricePaise
    imageUrl   = this@toProto.imageUrl
    inStock    = this@toProto.inStock
    category   = this@toProto.category
}

// ── In-memory seed data (swap for DB in production) ──────────
object ProductRepository {

    private val products = listOf(
        ProductEntity("p001", "Wireless Headphones",    249900, "https://example.com/img/headphones.jpg", true,  "electronics"),
        ProductEntity("p002", "Mechanical Keyboard",    599900, "https://example.com/img/keyboard.jpg",   true,  "electronics"),
        ProductEntity("p003", "USB-C Hub",              149900, "https://example.com/img/hub.jpg",        false, "electronics"),
        ProductEntity("p004", "Standing Desk Mat",       89900, "https://example.com/img/mat.jpg",        true,  "accessories"),
        ProductEntity("p005", "Monitor Light Bar",      129900, "https://example.com/img/lightbar.jpg",   true,  "accessories"),
        ProductEntity("p006", "Laptop Backpack",        349900, "https://example.com/img/backpack.jpg",   true,  "accessories"),
        ProductEntity("p007", "Noise-Cancelling Buds",  179900, "https://example.com/img/buds.jpg",       true,  "electronics"),
        ProductEntity("p008", "Portable Charger 20k",    99900, "https://example.com/img/charger.jpg",    false, "electronics"),
    )

    fun findById(id: String): ProductEntity? = products.firstOrNull { it.id == id }

    fun list(category: String): List<ProductEntity> =
        if (category.isBlank()) products
        else products.filter { it.category == category }
}
